Add Composer support
GaryJones/Gamajo-Dashboard-Glancer pull request #9
Opened 2018-01-14 17:21 UTC by mundschenk-at

Make a Composer package out of Gamjo-Dashboard-Glancer for ease of use in new plugins.

2018-01-15 07:55 UTC, GaryJones requested changes
Couple of minor tweaks, then it would be good to go. Thanks!

2018-01-15 07:55 UTC, GaryJones commented on composer.json
> +  "homepage": "http://github.com/GaryJones/Gamajo-Dashboard-Glancer",
`https` please.

2018-01-15 07:55 UTC, GaryJones commented on composer.json
> +      "homepage": "http://gamajo.com",
`https` please.

2018-01-15 08:53 UTC, mundschenk-at commented
Yes, of course this should be `https`. I'll fix the protocol tonight. (On a sidenote, you should probably check `gamajo/template-loader` for this as well, as that was my template for the `composer.json`.)

2018-01-15 15:44 UTC, GaryJones commented
> On a sidenote, you should probably check gamajo/template-loader for this as well, as that was my template for the composer.json

https://github.com/GaryJones/Gamajo-Template-Loader/commit/6129b825a81e9a55fa9ccdb72eea307d544f864b, thanks!

2018-01-15 15:59 UTC, mundschenk-at commented
Done :)

2018-01-15 16:00 UTC, GaryJones approved these changes

2018-01-15 16:00 UTC, merged

2018-01-15 16:00 UTC, GaryJones commented
Thank you :-)

2018-01-16 11:07 UTC, mundschenk-at commented
@GaryJones Could you please also add the package on `packagist.org`? Then I can delete the custom repository from my project's `composer.json`.

2018-01-16 12:54 UTC, GaryJones commented
@mundschenk-at I've moved this repo from `GaryJones` account on GitHub to `Gamajo`, and renamed it to match the Composer package name.

I've then registered it as https://packagist.org/packages/gamajo/dashboard-glancer.

When I get chance, I may update the file-level DocBlocks, but have no plans for changing anything code-wise.

2018-01-16 13:31 UTC, mundschenk-at commented
Thanks!